split/engine/urls.py
from django.urls import path
from django.conf import settings
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path('register', views.register_view, name='register'),
    path('login', views.login_view, name="login"),
    path('home', views.menu_view, name="home"),
    path('about', views.about_view, name="about"),
    path('history', views.history_view, name="history"),
    path('logout', views.logout_user, name="logout"),
    path('add_local',views.add_local,name='add_local'),
    path('remove_local/<int:pk>',views.remove_local,name='remove_local'),
    path('add_friend',views.add_friend,name='add_friend'),
    path('add_item',views.add_item,name='add_item'),
    path('order_item/<int:pk>',views.order_item,name='order_item'),
    path('new_bill/<int:pk>',views.new_bill,name='new_bill'),
    path('edit_friend/<int:pk>',views.edit_friend ,name="edit_friend"),
    path('bill/<int:pk>',views.bill,name='bill'),
    path('delete_order/<int:pk>',views.delete_orden,name='delete_orden'),
    path('order_detail/<int:pk>',views.order_detail,name='order_detail'),
    path('remove_bill/<int:pk>',views.remove_bill,name='remove_bill'),
    path('client_detail/<int:pk>',views.client_detail,name='client_detail'),
    path('generate_bills/<int:pk>',views.generate_bills,name='generate_bills'),
    path('view_bill/<int:pk>',views.view_bill,name='view_bill'),
]

split/split/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("engine.urls")),
]

split/engine/forms.py
from types import ClassMethodDescriptorType
from django import forms
from  django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.forms import fields
from django.forms.widgets import PasswordInput,TextInput,TextInput

class UserRegisterForm(UserCreationForm):
    first_name = forms.CharField(label='Nombre', widget=forms.TextInput(attrs={'class':'form-control',"placeholder":"John"}))
    last_name = forms.CharField(label='Apellidos', widget=forms.TextInput(attrs={'class':'form-control',"placeholder":"Doe"}))
    username = forms.CharField(label='Usuario', widget=forms.TextInput(attrs={'class':'form-control',"placeholder":"John_Doe"}))
    email = forms.CharField(label='correo electronico',widget=forms.TextInput(attrs={'class':'form-control',"placeholder":"John@mail.com"}))
    password1 = forms.CharField(label='Contraseña', widget=forms.PasswordInput(attrs={'class':'form-control',"placeholder":"S3cuReP4ss_235"}))
    password2 = forms.CharField(label='Confirmar contraseña', widget=forms.PasswordInput(attrs={'class':'form-control',"placeholder":"S3cuReP4ss_235"}))

    class Meta:
        model = User
        fields = ('username','password1','password2','email','first_name','last_name')
        help_text = {k:"" for k in fields }

split/engine/views.py
from django.urls import reverse
from django.contrib.auth import login,logout,authenticate
from django.contrib import messages
from django.contrib.auth.models import User
from django.shortcuts import redirect, render
from .models import *
from django.http import HttpResponse,HttpResponseRedirect, request
from .forms import UserRegisterForm
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth.decorators import login_required
from django.views.defaults import page_not_found
from django.db.models import Sum
from django.core.mail import send_mail
from django.conf import settings
from django.template.loader import render_to_string

# Create your views here.

contador = Cuenta_func.objects.first()
#creacion de el objeto user con super usuario
superuser = User.objects.filter(is_superuser=True)
if contador is None:
    n_contador =Cuenta_func(cuenta_numero=1)
    n_contador.save()
if superuser.count() == 0:
    superuser=User.objects.create_user("Admin","Admin@Split.com","Password")
    superuser.is_superuser = True
    superuser.is_staff = True
    superuser.save()

def index(request):
    if not request.user.is_authenticated:
        return redirect("register")
    else: return redirect("home")

@csrf_protect
def register_view(request):
    if not request.user.is_authenticated:
        form = UserRegisterForm()
        if request.method == 'POST':
            form = UserRegisterForm(request.POST)
            if form.is_valid():
                form.save()
                user= form.cleaned_data.get('username')
                messages.success(request,'Cuenta registrada bajo el nombre de usuario de: '+ user)
                return redirect('login')
        context= {'form':form}
        return render(request, 'register.html',context)
    else: return redirect("home")

@login_required(login_url="login")
def menu_view(request):
    context={}
    usuario = cliente.objects.filter(correo=request.user.email).exists()
    if usuario:
        print("URL menu_view: Usuario ya existe en clientes")
    else:
        cliente.objects.create(usuario_main=request.user,nombres=request.user.first_name,apellidos=request.user.last_name,correo=request.user.email)

    open = cuenta.objects.filter(usuario=request.user,estado="Abierta").exists()
    if open:
        cuentax = cuenta.objects.get(usuario=request.user,estado="Abierta")
        context['open'] = True
        return redirect(f"/bill/{cuentax.pk}")

    context['amigos'] = cliente.objects.filter(usuario_main=request.user).exclude(correo=request.user.email).order_by('nombres')
    context['locales'] = local.objects.filter(creador=request.user).order_by('nombre')
    return render(request,'menu.html',context)

@csrf_protect
def login_view(request):
    if not request.user.is_authenticated:
        if request.method == "POST":
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username,password=password)

            if user is not None:
                login(request,user)
                return redirect('home')
            else:
                messages.info(request, 'Nombre de usuario o contraseña incorrecta')
        context = {}
        return render(request,"login.html",context)
    else: return redirect("home")

def about_view(request):
    context = {}
    openx = cuenta.objects.filter(usuario=request.user,estado="Abierta").exists()
    if openx:

        context['open'] = True
    return render(request,"about.html",context)

def history_view(request):
    context = {}
    context['cuentas'] = cuenta.objects.filter(usuario=request.user,estado="Cerrada")
    return render(request,"history.html",context)

def logout_user(request):
    logout(request)
    return redirect('login')

@login_required(login_url="")
def add_local(request):
    if request.method == "POST":
        Nombre_local = request.POST.get('nombre_local')
        descripcion_local = request.POST.get('descripcion_local')
        existe = local.objects.filter(creador=request.user,nombre=Nombre_local).exists()

        if existe:
            messages.error(request,"Ese local ya se encuentra registrado")
        else:
            messages.info(request,"Local registrado con exito")
            local.objects.create(creador=request.user,nombre=Nombre_local,descripcion=descripcion_local)

        return redirect('home')

@login_required(login_url="")
def remove_local(request,pk):
    if request.method == "POST":

        local.objects.get(pk=pk).delete()
        messages.info(request,"Local eliminado con exito")
        return redirect('home')

@login_required(login_url="")
def add_friend(request):
    if request.method == "POST":
        nombres = request.POST.get('nombres_friend')
        apellidos = request.POST.get('apellidos_friend')
        correo = request.POST.get('email_friend')

        existe = cliente.objects.filter(usuario_main=request.user,correo=correo).exists()

        if existe:
            messages.error(request,"Ese correo ya se encuentra registrado para otro usuario")
        else:
            messages.info(request,"amigo registrado con exito")
            cliente.objects.create(usuario_main=request.user,nombres=nombres,apellidos=apellidos,correo=correo)

        return redirect('home')

@login_required(login_url="")
def edit_friend(request,pk):
    if request.method == "POST":
        nombres = request.POST.get('nombres_friend_edit')
        apellidos = request.POST.get('apellidos_friend_edit')
        correo = request.POST.get('email_friend_edit')

        amigo = cliente.objects.get(pk=pk)
        existe = cliente.objects.filter(correo=correo).exclude(pk=pk).exists()

        if existe:
            messages.error(request,"Ese correo ya se encuentra registrado para otro usuario")
        else:
            amigo.nombres = nombres
            amigo.apellidos = apellidos
            amigo.correo = correo
            amigo.save()
            messages.info(request,"amigo editado con exito")


        return redirect('home')

@login_required(login_url="")
def new_bill(request,pk):
    if request.method == "POST":
        clientes=request.POST.getlist('FriendBox')
        user=cliente.objects.get(correo=request.user.email)
        clientes.append(user.pk)
        alias=request.POST.get('alias')

        locals = local.objects.get(pk=pk)

        cuenta.objects.create(alias=alias,local=locals,usuario=request.user)
        clientex=[]
        for x in range(0,len(clientes)):
            clientex.append(cliente.objects.get(pk=clientes[x]))
        cuenta.objects.filter(usuario=request.user).last().clientes.add(*clientex)
        context={}

        context['clientes'] = clientex
        context['local'] = locals
        return redirect(f"/bill/{pk}" ,context)

@login_required(login_url="")
def bill(request,pk):
    context={}
    open = cuenta.objects.filter(usuario=request.user,estado="Abierta").exists()
    if open:
        cuentax = cuenta.objects.get(usuario=request.user,estado="Abierta")
        context['open'] = True
        context['ordenes'] = orden.objects.filter(cuenta=cuentax).all()
        context['cuenta'] = cuentax
        context['clientes'] = cuentax.clientes.all()
        context['items'] = item.objects.filter(usuario_main=request.user)
        context['splits'] = split.objects.filter(cuenta=cuentax).order_by('cliente')

        obj = orden.objects.filter(cuenta=cuentax).all().aggregate(Sum('subtotal'))
        subtotal= obj['subtotal__sum']
        obj = orden.objects.filter(cuenta=cuentax).all().aggregate(Sum('subtotal_iva'))
        subtotal_iva= obj['subtotal_iva__sum']

        cuentax.subtotal = subtotal
        cuentax.total = subtotal_iva
        if subtotal:
            cuentax.monto_propina = float(subtotal) * 0.10
            cuentax.save()
            cuentax.total_propina = float(cuentax.total) + float(cuentax.monto_propina)
            cuentax.save()
            context['monto_propinap'] = cuentax.monto_propina / cuentax.clientes.count()


    return render(request,"bill.html",context)

@login_required(login_url="")
def add_item(request):
    if request.method == "POST":
        nombre = request.POST.get('nombre_item')
        descripcion = request.POST.get('descripcion_item')
        precio = request.POST.get('precio_item')
        iva = request.POST.get('incluye_iva_item')
        if iva is None:
            precio_iva = float(precio) * 0.15
            item.objects.create(nombre=nombre,descripcion=descripcion,precio=precio,iva=False,monto_iva=precio_iva,usuario_main=request.user)

        else:
            item.objects.create(nombre=nombre,descripcion=descripcion,precio=precio,usuario_main=request.user)


        return redirect('home')

@login_required(login_url="")
def order_item(request,pk):
    if request.method == "POST":
        cuentax = cuenta.objects.filter(usuario=request.user,estado="Abierta").last()
        clienteslist= cuentax.clientes.values("pk")

        for clientei in clienteslist:
            cliente_inst=cliente.objects.get(pk=clientei['pk'])
            split_state = split.objects.filter(cuenta=cuentax,cliente=cliente_inst).exists()
            if split_state:
                print("URL order_item: Split ya existe")
            else:
                split.objects.create(cuenta=cuentax,cliente=cliente_inst)


        itemorder = item.objects.get(pk=pk)
        Consumo = request.POST.get('Consumo_individual',"compartida")
        if Consumo == "individual":
            orden.objects.create(item=itemorder,cuenta=cuentax)
            ordenx = orden.objects.filter(item=itemorder,cuenta=cuentax).last()
            numbers=request.POST.getlist('num')
            clientesInsert = []
            for clientei in clienteslist:
                clientesInsert.append(cliente.objects.get(pk=clientei['pk']))
            for x in range(0,len(numbers)):
                if int(numbers[x])>0:

split/engine/templates/about.html
{% extends "layout.html" %}
{% block Title %} Acerca de split {% endblock %}
{% block body %} 

<div class="container bg-light Menu rounded py-5 shadow-lg">
    <div class="row">
		<div class="col-md-6">
            <div class="card about-card">
                <img src="/static/SplitLogo.png" class="card-img-top" alt="...">
                <div class="card-body text-center">
                    <h2>¿Que es split?</h2>
                  <p class="card-text">Split es una plataforma que se encarga de dividir la cuenta entre tu y tus amigos en una mesa según el consumo personal de cada miembro de la mesa.</p>
                  <p>solo creas una mesa, colocas los nombre de cada persona, agregas los productos consumidos seleccionando a cada persona que consumió dicho producto, Split te dividirá la cantidad de dinero que le corresponde a cada uno, el IVA y la propina, también guardara un registro de cada una de tus cuentas para que puedas revisarlas cuando desees</p>
                </div>
                <img src="/static/PayingBill2Purple.png" class="card-img-top" alt="...">
              </div>
              <hr>
		</div>
		<div class="col-md-6">
			<div class="card about-card">
                <img src="/static/RestaurantTalkYellow.png"class="card-img-top" alt="...">
                <div class="card-body text-center">
                    <h2>Un claro ejemplo de ello</h2>
                  <p class="card-text">van 5 amigos junto a ti a un restaurante y cada quien pide diferente cantidad de bebidas y postres pero todos comparten ciertos platillos como bandejas de alitas o surtidos, por lo que a la hora de pagar la cuenta no seria justo dividir equitativamente la cuenta, ahí es donde entra Split facilitando la tarea para ti y tus amigos.</p>
                  <p>Lo ves Split es super es sencillo facil de usar y util, animate a probarlo, se que te va a encantar.</p>
                </div>
                <img src="/static/SplitSlogan.png" class="card-img-top" alt="...">
              </div>
              <hr>
              <div class="text-center pt-5">
              {% if user.is_authenticated %}
              <a href='home' class="btn btn-primary">Ir al menu principal</a>
              {% else %}
              <a href='register' class="btn btn-primary m-2">Registrarse</a>
              <a href='login' class="btn btn-secondary m-2 ">Iniciar sesion</a>
              {% endif %}
            </div>
		</div>
	</div>
</div>

{% endblock %}

split/engine/templates/client_detail.html
{% extends "layout.html" %}
{% block Title %} Historial de cliente {% endblock %}
{% block body %} 

<div class="container bg-light Menu rounded py-5 shadow-lg">


  {% if messages %}
  <div class="row m-2">
  <div class="col-lg text-center">
      {% for message in messages %}
      <div class="alert alert-dismissible fade show alert-{{ message.tags }}" role="alert">
          <p>{{ message }}</p>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      {% endfor %}
    </div>

  </div>
{% endif %}

    
      <div class="tab-content overflow" id="pills-tabContent">
        <div class="tab-pane fade show active" id="pills-general" role="tabpanel" aria-labelledby="pills-general-tab">
          {%if consumos %}
          <h2 class="text-center">Consumos detallados de {{split.cliente.nombres}} {{split.cliente.apellidos}}</h2>  
          <div class="text-left"><a class="btn btn-primary btn-lg mt-0 mb-5 mx-4" href="/home"><i class="fas fa-long-arrow-alt-left"></i>  Regresar</a></div>
          <table class="table text-light table-dark table-hover text-center">
            <thead>
            <tr>
            <th>Orden</th>
            <th>Cantidad</th>
            <th>Total</th>
            <th>Precio unitario</th>
            <th>consumido</th>
            <th>split</th>
            <th></th>
          </tr>
            </thead>
        <tbody>
          {% for consumo in consumos %}
      <tr>
        
            <th>{{consumo.orden.item.nombre}}</th>
            <th>{{consumo.orden.cantidad_total}}</th>
            <th>{{consumo.orden.subtotal_iva}} $</th>
            <th>{{consumo.orden.item.precio}} $</th>
            <th>{%if consumo.orden.dividido %}Consumo compartido{%else%}Consumo individual: {{consumo.cantidad}}{%endif%}</th>
            <th>{{consumo.monto_iva}} $</th>
            <th><a class="btn btn-secondary btn-sm" href="/order_detail/{{consumo.orden.pk}}">Detalles <i class="far fa-eye"></i></a></th>
      </tr>
      {%endfor%}
          </tbody>
          </table>
      {%else%}
      <h2 class="text-center">Parece que {{split.cliente.nombres}} {{split.cliente.apellidos}} no posee ningun consumo aun...</h2>  
      <div class="text-left"><a class="btn btn-primary btn-lg mt-0 mb-5 mx-4" href="/home"><i class="fas fa-long-arrow-alt-left"></i>  Regresar</a></div>
      {%endif%}
    </div>

<script>

function EnableDisable(option) {
if (option.checked) {
  $('.num').attr("hidden",false);
  $('.check').attr("hidden",true);
  $(".Consumo_individual").prop( "checked", true );
  $(".divided").attr("hidden",true);

} else {

  $('.num').attr("hidden",true);
  $('.check').attr("hidden",false);
  $(".Consumo_individual").prop( "checked", false );
  $(".divided").attr("hidden",false);

}             
}   

function CheckOrder(event){
  if($("#Consumo_individual_check").prop("checked")){
    var valid = false;
      $(".num").each(function(){
        if(this.value != 0){
          valid = true;
        }
      });
      if (valid){
        console.log("todo bien joven")
      }
      else{
        event.preventDefault();
        alert("Debes seleccionar el consumo para al menos una persona.")
      }
  }
  else{
    contador=$('[name="check"]:checked').length
    if(contador < 2){
        alert("Debes seleccionar el consumo para al menos dos persona.");
        event.preventDefault();
    }
  }
}

</script>
{% endblock %}

split/engine/templates/email.html
<h1>Hola {{splitx.cliente.nombres}} {{splitx.cliente.apellidos}}</h1>

<h2>Tienes una cuenta que {{cuenta.usuario.first_name}} {{cuenta.usuario.last_name}} creo con sus amigos</h2>

<h2>Lugar:{{cuenta.local.nombre}}</h2>
<h2>Fecha:{{cuenta.fecha_hora}}</h2>
<h2>Ocacion:{{cuenta.alias}}</h2>

<h3>Aca tienes todos los detalles:</h3>

<table cellpadding="2" cellspacing="3" align="left" border="1">
    <thead>
      <tr>
    <th>Nombre</th>
    <th>Precio</th>
    <th>Cantidad</th>
    <th>Tipo</th>
    <th>subtotal</th>
    <th>+IVA</th>
  </tr>
    </thead>
<tbody>
{% for orden in ordenes %}
<tr>
<th>{{orden.item.nombre}}</th>
<th>{{orden.item.precio}} $</th>
<th>{{orden.cantidad_total }}</th>
<th>{% if orden.dividido%}Orden dividida{% else %}Consumo individual{%endif%}</th>
<th>{{orden.subtotal }} $</th>
<th>{{orden.subtotal_iva}} $</th>
</tr>
{%endfor%}

<tr>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <tr>
    <th></th>
    <th></th>
    <th></th>
    <th>=</th>
    <th>{{cuenta.subtotal}} $</th>
    <th>{{cuenta.total}} $</th>
  </tr>
  {%if cuenta.propina %}
  <tr>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th>Gran Total</th>
    <th>{{cuenta.total_propina}}</th>
  </tr>
  {%endif%}
</tbody>
</table>

<div style="margin-top: 100px; padding: 30px;">

    <h2 class="text-center">Consumos detallados de {{splitx.cliente.nombres}} {{splitx.cliente.apellidos}}</h2>
</div>

    <div>
          <table cellpadding="2" cellspacing="3" align="left" border="1">
            <thead>
            <tr>
            <th>Orden</th>
            <th>Cantidad</th>
            <th>Total</th>
            <th>Precio unitario</th>
            <th>consumido</th>
            <th>split</th>
          </tr>
            </thead>
        <tbody>
          {% for consumo in consumos %}
      <tr>
            <th>{{consumo.orden.item.nombre}}</th>
            <th>{{consumo.orden.cantidad_total}}</th>
            <th>{{consumo.orden.subtotal_iva}} $</th>
            <th>{{consumo.orden.item.precio}} $</th>
            <th>{%if consumo.orden.dividido %}Consumo compartido{%else%}Consumo individual: {{consumo.cantidad}}{%endif%}</th>
            <th>{{consumo.monto_iva}} $</th>
      </tr>
      {%endfor%}
          </tbody>
          </table>
        </div>  

        <div style="margin-top: 100px; padding: 30px;">

            <h2 class="text-center">Consumos de todos tus amigos</h2>
        </div>

        <table cellpadding="2" cellspacing="3" align="left" border="1">
            <thead>
              <tr>
            <th>Nombres</th>
            <th>Apellidos</th>
            <th>Correo</th>
            <th>Split</th>
            <th class="Propina">Propina</th>
          </tr>
            </thead>
        <tbody>
      {% for split in splits %}
      <tr>
        <th>{{split.cliente.nombres}}</th>
            <th>{{split.cliente.apellidos}}</th>
            <th>{{split.cliente.correo}}</th>
            <th>{{split.monto}} $</th>
            <th class="Propina">{%if cuenta.propina %}{{split.monto_propina}}{%endif%}</th>
          </tr>
      {%endfor%}
        </tbody>
          </table>

split/engine/templates/history.html
{% extends "layout.html" %}
{% block Title %} Historial {% endblock %}
{% block body %} 

<div class="container bg-light Menu rounded py-5 shadow-lg">´
    <div class="row">
    {%for cuenta in cuentas %}
    <div class="col">
        <div class="card about-card shadow-lg border-primary">
            <div class="card-body text-left">
                <h3>{{cuenta.local.nombre}}: {{cuenta.alias}}</h3>
                <h3>{{cuenta.fecha_hora}}</h3>
                <h3>{{cuenta.total}} $</h3>
                <p>con: {%for p in cuenta.clientes.all %}{{p.nombres}} {{p.apellidos}}, {%endfor%}</p>
                <div class="container text-center">
                <a class="btn btn-secondary btn-lg m-3" href="/view_bill/{{cuenta.pk}}">Revisar cuenta  <i class="far fa-eye"></i></a>
              </div>
            </div>
          </div>
        </div>
    {%endfor%}
</div>

</div>

{% endblock %}

split/engine/templates/register.html
{% extends "layout.html" %}
{% block Title %} Registrarse {% endblock %}
{% block body %} 
<div class="container mt-5">
    <div class="row">
      <div class="col-lg-10 col-xl-10 mx-auto">
        <div class="card flex-row my-5 border-0 shadow rounded-3 overflow-hidden">
          <div class="card-img-left d-none d-md-flex reg">
          </div>
          <div class="card-body p-4 p-sm-8">
            <h5 class="card-title text-center mb-5 fw-light fs-5">Registro de usuario</h5>

            {% if form.errors %}
            <div class="container">       
              <div class="alert alert-danger" role="alert">
                {{ form.errors }}
              </div>
            </div>
            {% endif %}
            
            <form method="post" action="">
              <!-- {{form} -->

              {% csrf_token %}

              <div class="form mb-3">
                <!-- <input type="text" class="form-control" id="floatingInputName" placeholder="Tonny" required autofocus>
                <label for="floatingInputUsername">Nombre</label> -->
                <label for="id_last_name">
                  {{ form.first_name.label }}
                </label>
                {{ form.first_name }}
              </div>

              <div class="form mb-3">
                <!-- <input type="text" class="form-control" id="floatingInputSurname" placeholder="Montenegro" required>
                <label for="floatingInputEmail">Apellido</label> -->
                <label for="id_last_name">
                  {{ form.last_name.label }}
                </label>
                {{ form.last_name }}
              </div>

              <div class="form mb-3">
                <!-- <input type="email" class="form-control" id="floatingInputEmail" placeholder="Tonny@mail.com" required>
                <label for="floatingInputEmail">Correo electronico</label> -->
                <label for="id_email">
                  {{ form.email.label }}
                </label>
                {{ form.email }}
              </div>

              <!-- <div class="form-floating mb-3">
                <input type="tel" class="form-control" id="floatingInputNumber" placeholder="83854816" required>
                <label for="floatingInputEmail">Numero</label>
              </div> -->

              <hr>

              <div class="form mb-3">
                <!-- <input type="password" class="form-control" id="floatingPassword" placeholder="Password" required>
                <label for="floatingPassword">Contraseña</label> -->
                <label for="id_username">
                  {{ form.username.label }}
                </label>
                {{ form.username }}
              </div>

              <div class="form mb-3">
                <!-- <input type="password" class="form-control" id="floatingPassword" placeholder="Password" required>
                <label for="floatingPassword">Contraseña</label> -->
                <label for="id_password1">
                  {{ form.password1.label }}
                </label>
                {{ form.password1 }}
              </div>

              <div class="form mb-3">
                <!-- <input type="password" class="form-control" id="floatingPasswordConfirm" placeholder="Confirm Password" required>
                <label for="floatingPasswordConfirm">Confirmar Contraseña</label> -->
                <label for="id_password1">
                {{ form.password2.label }}
                </label>
                {{ form.password2 }}
                
              </div> 

              <div class="d-grid mb-2">
                <button class="btn btn-lg btn-primary btn-login fw-bold text-uppercase" type="submit" name="create_user">Registrarse</button>
              </div>

            </form>
            <a class="d-block text-center mt-2 small" href="login">Ya tiene una cuenta? Iniciar sesion</a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}